/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import javafx.beans.property.ReadOnlyStringWrapper;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.RowConstraints;
import javafx.util.Callback;

public class FichaMedicaBoundary implements Boundary {
    private TextField txtTipoSanguineo = new TextField();
    private TextField txtPeso = new TextField();
    private TextField txtAlergias = new TextField();
    private TableView<FichaMedica> tabela = new TableView<>();
    

    public void tableCreation() {
        TableColumn<FichaMedica, String> col1 = new TableColumn<>("Tipo Sanguineo");
        col1.setCellValueFactory(c -> new ReadOnlyStringWrapper(c.getValue().getTipoSanguineo()));

        TableColumn<FichaMedica, String> col2 = new TableColumn<>("Peso");
        col2.setCellValueFactory(c -> new ReadOnlyStringWrapper(String.valueOf(c.getValue().getPeso())));

        TableColumn<FichaMedica, String> col3 = new TableColumn<>("Alergias");
        col3.setCellValueFactory(c -> new ReadOnlyStringWrapper(c.getValue().getAlergias()));

        TableColumn<FichaMedica, Void> col4 = new TableColumn<>("Ações");
        Callback<TableColumn<FichaMedica, Void>, TableCell<FichaMedica, Void>> cellFactory
                = (tablecolumn) -> new TableCell<>() {
                    private Button btnApagar = new Button("Apagar");
                    {
                        btnApagar.setDisable( true );
                        btnApagar.setOnAction( e -> {
                        });
                    }
                    @Override
                    public void updateItem(Void item, boolean empty) {
                        if (empty) {
                            setGraphic(null);
                        } else {
                            setGraphic( btnApagar );
                        }
                    }
                };
        col4.setCellFactory( cellFactory );
        tabela.getColumns().addAll( col1, col2, col3, col4);
    }

    public Pane render() { 
        BorderPane panePrincipal = new BorderPane();
        GridPane paneForm = new GridPane();
        HBox paneBotoes = new HBox();

        // Gera as colunas da tabela
        tableCreation();

        ColumnConstraints colLabel = new ColumnConstraints();
        colLabel.setPercentWidth(30);

        ColumnConstraints colTextField = new ColumnConstraints();
        colTextField.setPercentWidth(70);

        RowConstraints linha = new RowConstraints();
        linha.setPrefHeight(50);

        paneForm.getColumnConstraints().addAll(colLabel, colTextField);
        paneForm.getRowConstraints().addAll(linha, linha, linha, linha, linha);

        paneForm.add( new Label("Tipo Sanguineo"), 0, 0);
        paneForm.add( txtTipoSanguineo, 1, 0);
        paneForm.add( new Label("Peso:"), 0, 1);
        paneForm.add( txtPeso, 1, 1);
        paneForm.add( new Label("Alergias:"), 0, 2);
        paneForm.add( txtAlergias, 1, 2);

        Button btnSalvar = new Button("Salvar");

        btnSalvar.setOnAction( evento -> {
            new Alert(AlertType.INFORMATION, 
                "FichaMedoca gravada com sucesso", 
                            ButtonType.OK).show();
        });

        Button btnPesquisar = new Button("Pesquisar");

        btnPesquisar.setOnAction( evento -> {

        });

        paneBotoes.getChildren().addAll(btnSalvar, btnPesquisar);

        paneForm.add( paneBotoes, 0, 4, 2, 1);

        panePrincipal.setTop( paneForm );
        panePrincipal.setCenter( tabela );

        return panePrincipal;
    }
}
