/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertTrue(true);
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
