/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class App extends Application {

    public void start(Stage stage) { 
        BorderPane panePrincipal = new BorderPane();
        GridPane paneForm = new GridPane();
        HBox paneBotoes = new HBox();

        Scene scn = new Scene(panePrincipal, 800, 600);

        TextField txtNome = new TextField();
        TextField txtTelefone = new TextField();
        TextField txtEmail = new TextField();
        DatePicker dtaNascimento = new DatePicker();

        // Label lblNome = new Label("Nome");
        paneForm.add( new Label("Nome:"), 0, 0);
        paneForm.add( txtNome, 1, 0);
        paneForm.add( new Label("Telefone:"), 0, 1);
        paneForm.add( txtTelefone, 1, 1);
        paneForm.add( new Label("Email:"), 0, 2);
        paneForm.add( txtEmail, 1, 2);
        paneForm.add( new Label("Nascimento:"), 0, 3);
        paneForm.add( dtaNascimento, 1, 3);

        Button btnSalvar = new Button("Salvar");
        Button btnPesquisar = new Button("Pesquisar");
        paneBotoes.getChildren().addAll(btnSalvar, btnPesquisar);

        paneForm.add( paneBotoes, 0, 4, 2, 1);

        panePrincipal.setCenter( paneForm );

        stage.setScene(scn);
        stage.setTitle("Agenda de Contato");
        stage.show();
    }

    public static void main(String[] args) {
        Application.launch(App.class, args);
    }
}
