/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.RowConstraints;
import javafx.stage.Stage;


// class Gravar implements EventHandler<ActionEvent> { 
//     public void handle(ActionEvent e) { 
//         Contato c1 = new Contato(
//             txtNome.getText(), 
//             txtTelefone.getText(), txtEmail.getText(), 
//             dtaNascimento.getValue()
//         );
//     }
// }


public class App extends Application {

    private List<Contato> lista = new ArrayList<>();

    public void start(Stage stage) { 
        BorderPane panePrincipal = new BorderPane();
        GridPane paneForm = new GridPane();
        HBox paneBotoes = new HBox();

        ColumnConstraints colLabel = new ColumnConstraints();
        colLabel.setPercentWidth(30);

        ColumnConstraints colTextField = new ColumnConstraints();
        colTextField.setPercentWidth(70);

        RowConstraints linha = new RowConstraints();
        linha.setPrefHeight(50);

        paneForm.getColumnConstraints().addAll(colLabel, colTextField);
        paneForm.getRowConstraints().addAll(linha, linha, linha, linha, linha);

        Scene scn = new Scene(panePrincipal, 800, 600);

        TextField txtNome = new TextField();
        TextField txtTelefone = new TextField();
        TextField txtEmail = new TextField();
        DatePicker dtaNascimento = new DatePicker();

        Label lblNome = new Label("Nome");
        lblNome.setStyle("-fx-background-color: 'yellow'; -fx-font-size: 25px; -fx-width: '100%'; -fx-height: '100%'; -fx-rotate: 45");
        paneForm.add( lblNome, 0, 0);
        paneForm.add( txtNome, 1, 0);
        paneForm.add( new Label("Telefone:"), 0, 1);
        paneForm.add( txtTelefone, 1, 1);
        paneForm.add( new Label("Email:"), 0, 2);
        paneForm.add( txtEmail, 1, 2);
        paneForm.add( new Label("Nascimento:"), 0, 3);
        paneForm.add( dtaNascimento, 1, 3);

        Button btnSalvar = new Button("Salvar");

        // EventHandler<ActionEvent> gravar = new EventHandler<>(){
        //     public void handle(ActionEvent evento) { 
        //         Contato c1 = new Contato(
        //             txtNome.getText(), 
        //             txtTelefone.getText(), txtEmail.getText(), 
        //             dtaNascimento.getValue()
        //         );
        //         lista.add(c1);
        //         new Alert(AlertType.INFORMATION, 
        //             "Contato gravado com sucesso", 
        //                         ButtonType.OK).show();
        //     }
        // };

        // EventHandler<ActionEvent> gravar = ( ActionEvent evento ) -> { 
        // btnSalvar.addEventHandler(ActionEvent.ANY, gravar);
        // EventHandler<ActionEvent> gravar = evento -> { 
        // btnSalvar.addEventHandler(ActionEvent.ANY, ( evento )-> {
        btnSalvar.setOnAction( evento -> {
            Contato c1 = new Contato(
                    txtNome.getText(), 
                    txtTelefone.getText(), txtEmail.getText(), 
                    dtaNascimento.getValue()
                );
            lista.add(c1);
            new Alert(AlertType.INFORMATION, 
                "Contato gravado com sucesso", 
                            ButtonType.OK).show();
        });

        

        Button btnPesquisar = new Button("Pesquisar");

        btnPesquisar.setOnAction( evento -> {
            for (Contato c : lista) { 
                if ( c.nome().contains( txtNome.getText() )) { 
                    txtNome.setText( c.nome() );
                    txtTelefone.setText( c.telefone() );
                    txtEmail.setText( c.email() );
                    dtaNascimento.setValue( c.nascimento() );
                    break;
                }
            }
        });

        paneBotoes.getChildren().addAll(btnSalvar, btnPesquisar);

        paneForm.add( paneBotoes, 0, 4, 2, 1);

        panePrincipal.setCenter( paneForm );

        stage.setScene(scn);
        stage.setTitle("Agenda de Contato");
        stage.show();
    }

    public static void main(String[] args) {
        Application.launch(App.class, args);
    }
}
