/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import java.time.LocalDate;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class ContatoBoundary extends Application {
    private TextField txtNome = new TextField();
    private TextField txtTelefone = new TextField();
    private TextField txtEmail = new TextField();
    private DatePicker dtaNascimento = new DatePicker();

    private ContatoControl control = new ContatoControl();

    public void start(Stage stage) { 
        BorderPane panePrincipal = new BorderPane();
        GridPane paneForm = new GridPane();
        HBox paneBotoes = new HBox();

        panePrincipal.setCenter( paneForm );

        ColumnConstraints coluna1 = new ColumnConstraints();
        coluna1.setPercentWidth(30);

        ColumnConstraints coluna2 = new ColumnConstraints();
        coluna2.setPercentWidth(70);

        paneForm.getColumnConstraints().addAll( coluna1, coluna2 );

        Label lblNome = new Label("Nome:");
        lblNome.setStyle("-fx-font-size: 20px; -fx-background-color: 'yellow'; -fx-rotate: -45; -fx-text-fill: 'red'; -fx-font-weigth: 'bold';");
        paneForm.add( lblNome, 0, 0);
        paneForm.add( txtNome, 1, 0);
        paneForm.add( new Label("Telefone: "), 0, 1);
        paneForm.add( txtTelefone, 1, 1);
        paneForm.add( new Label("Email: "), 0, 2);
        paneForm.add( txtEmail, 1, 2);
        paneForm.add( new Label("Nascimento: "), 0, 3);
        paneForm.add( dtaNascimento, 1, 3);

        paneForm.add( paneBotoes, 0, 4, 2, 1);

        Button btnSalvar = new Button("Salvar");
        Button btnPesquisar = new Button("Pesquisar");

        btnSalvar.setOnAction( evento -> {
            Contato c = telaParaContato();
            control.adicionar(c);
            new Alert( AlertType.INFORMATION, 
                "Contato salvo com sucesso", ButtonType.OK).show();
            txtNome.setText("");
            txtTelefone.setText("");
            txtEmail.setText("");
            dtaNascimento.setValue(LocalDate.now());
        } );

        btnPesquisar.setOnAction( evento -> {
            Contato c = 
                control.pesquisarPorNome( txtNome.getText() );
            contatoParaTela( c );
        });

        paneBotoes.getChildren().addAll(btnSalvar, btnPesquisar);

        Scene scn = new Scene( panePrincipal, 800, 600);
        stage.setScene(scn);
        stage.setTitle("Agenda de Contatos");
        stage.show();
    }

    public Contato telaParaContato() { 
        Contato c = new Contato();
        c.setNome( txtNome.getText() );
        c.setTelefone( txtTelefone.getText() );
        c.setEmail( txtEmail.getText() );
        c.setNascimento( dtaNascimento.getValue() );
        return c;
    }

    public void contatoParaTela( Contato c ) {
        if (c != null) {
            txtNome.setText( c.getNome() );
            txtTelefone.setText( c.getTelefone() );
            txtEmail.setText( c.getEmail() );
            dtaNascimento.setValue( c.getNascimento() );
        }
    }

    public static void main(String[] args) {
       Application.launch(ContatoBoundary.class, args);
    }
}
